### ISSUE TITLE
Can't edit image

### ISSUE THREAD

**Issue by hvelarde** [zopyx/zopyx.ipsumplone#1]
Plone 4.3.8 with plone.app.contenttypes installed; try to edit the image and you will get an "incorrect object type" error (or something like that):

![selection_013](https://cloud.githubusercontent.com/assets/341393/13820721/57f8f2da-eb7d-11e5-9e55-6d933031dcb2.png)

**Comment by zopyx** [comment]
Should be fixed in 

https://pypi.python.org/pypi/zopyx.ipsumplone/0.3.7
